name: alfre
favicon: null
layout_spectrum: 0.29262170824222267
typography_spectrum: 0.9483730781357735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#12100f'
    - '#4e5b3d'
    - '#688247'
    - '#9aa49a'
    - '#c6cccd'
  brandStrength: 0.08805888635106385
  lightness: 0.9551695564296097
  saturation: 0.45839108410291374
  rhythmicContrast: 0.02153238421306014
purpose: []
